# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_adminpanel_adduser.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(950, 338)
        MainWindow.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 141, 191))
        self.photo.setText("")
        self.photo.setScaledContents(True)
        self.photo.setWordWrap(False)
        self.photo.setOpenExternalLinks(False)
        self.photo.setObjectName("photo")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(170, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1.setFont(font)
        self.label1.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(170, 40, 91, 21))
        self.label2.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(170, 70, 91, 21))
        self.label3.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(170, 100, 91, 21))
        self.label4.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label4.setObjectName("label4")
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(540, 40, 111, 21))
        self.label9.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label9.setObjectName("label9")
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setGeometry(QtCore.QRect(540, 70, 111, 21))
        self.label10.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label10.setObjectName("label10")
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setGeometry(QtCore.QRect(540, 100, 111, 21))
        self.label11.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label11.setObjectName("label11")
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setGeometry(QtCore.QRect(540, 10, 361, 21))
        self.label8.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(170, 130, 211, 21))
        self.label5.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(170, 220, 91, 21))
        self.label6.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(170, 250, 91, 21))
        self.label7.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label7.setObjectName("label7")
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setGeometry(QtCore.QRect(530, 130, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label12.setFont(font)
        self.label12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label12.setAutoFillBackground(False)
        self.label12.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setGeometry(QtCore.QRect(540, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label13.setFont(font)
        self.label13.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label13.setObjectName("label13")
        self.label14 = QtWidgets.QLabel(self.centralwidget)
        self.label14.setGeometry(QtCore.QRect(170, 190, 151, 21))
        self.label14.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label14.setObjectName("label14")
        self.label_secondname = QtWidgets.QLineEdit(self.centralwidget)
        self.label_secondname.setEnabled(True)
        self.label_secondname.setGeometry(QtCore.QRect(270, 10, 261, 21))
        self.label_secondname.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_secondname.setText("")
        self.label_secondname.setReadOnly(True)
        self.label_secondname.setObjectName("label_secondname")
        self.label_name = QtWidgets.QLineEdit(self.centralwidget)
        self.label_name.setEnabled(True)
        self.label_name.setGeometry(QtCore.QRect(270, 40, 261, 21))
        self.label_name.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_name.setText("")
        self.label_name.setReadOnly(True)
        self.label_name.setObjectName("label_name")
        self.label_middlename = QtWidgets.QLineEdit(self.centralwidget)
        self.label_middlename.setEnabled(True)
        self.label_middlename.setGeometry(QtCore.QRect(270, 70, 261, 21))
        self.label_middlename.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_middlename.setText("")
        self.label_middlename.setReadOnly(True)
        self.label_middlename.setObjectName("label_middlename")
        self.label_rank = QtWidgets.QLineEdit(self.centralwidget)
        self.label_rank.setEnabled(True)
        self.label_rank.setGeometry(QtCore.QRect(270, 100, 261, 21))
        self.label_rank.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_rank.setText("")
        self.label_rank.setReadOnly(True)
        self.label_rank.setObjectName("label_rank")
        self.label_adoptdate = QtWidgets.QLineEdit(self.centralwidget)
        self.label_adoptdate.setEnabled(True)
        self.label_adoptdate.setGeometry(QtCore.QRect(390, 130, 141, 21))
        self.label_adoptdate.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_adoptdate.setText("")
        self.label_adoptdate.setReadOnly(True)
        self.label_adoptdate.setObjectName("label_adoptdate")
        self.label_post = QtWidgets.QLineEdit(self.centralwidget)
        self.label_post.setEnabled(True)
        self.label_post.setGeometry(QtCore.QRect(270, 250, 641, 21))
        self.label_post.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_post.setText("")
        self.label_post.setReadOnly(True)
        self.label_post.setObjectName("label_post")
        self.label_docsSerie = QtWidgets.QLineEdit(self.centralwidget)
        self.label_docsSerie.setEnabled(True)
        self.label_docsSerie.setGeometry(QtCore.QRect(660, 40, 251, 21))
        self.label_docsSerie.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_docsSerie.setText("")
        self.label_docsSerie.setReadOnly(True)
        self.label_docsSerie.setObjectName("label_docsSerie")
        self.label_docsNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.label_docsNumber.setEnabled(True)
        self.label_docsNumber.setGeometry(QtCore.QRect(660, 70, 251, 21))
        self.label_docsNumber.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_docsNumber.setText("")
        self.label_docsNumber.setReadOnly(True)
        self.label_docsNumber.setObjectName("label_docsNumber")
        self.label_docsDate = QtWidgets.QLineEdit(self.centralwidget)
        self.label_docsDate.setEnabled(True)
        self.label_docsDate.setGeometry(QtCore.QRect(660, 100, 251, 21))
        self.label_docsDate.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_docsDate.setText("")
        self.label_docsDate.setReadOnly(True)
        self.label_docsDate.setObjectName("label_docsDate")
        self.label_salary = QtWidgets.QLineEdit(self.centralwidget)
        self.label_salary.setEnabled(True)
        self.label_salary.setGeometry(QtCore.QRect(660, 160, 251, 21))
        self.label_salary.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_salary.setText("")
        self.label_salary.setReadOnly(True)
        self.label_salary.setObjectName("label_salary")
        self.label_checksum = QtWidgets.QLineEdit(self.centralwidget)
        self.label_checksum.setEnabled(True)
        self.label_checksum.setGeometry(QtCore.QRect(330, 190, 581, 21))
        self.label_checksum.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.label_checksum.setText("")
        self.label_checksum.setReadOnly(True)
        self.label_checksum.setObjectName("label_checksum")
        self.dataedit_btn_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.dataedit_btn_confirm.setEnabled(False)
        self.dataedit_btn_confirm.setGeometry(QtCore.QRect(10, 260, 141, 31))
        self.dataedit_btn_confirm.setCheckable(False)
        self.dataedit_btn_confirm.setObjectName("dataedit_btn_confirm")
        self.label_department = QtWidgets.QComboBox(self.centralwidget)
        self.label_department.setGeometry(QtCore.QRect(270, 220, 641, 21))
        self.label_department.setObjectName("label_department")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(730, 300, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_id.setFont(font)
        self.label_id.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label1_2.setGeometry(QtCore.QRect(690, 300, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.label1_2.setObjectName("label1_2")
        self.dataedit_btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.dataedit_btn_cancel.setEnabled(False)
        self.dataedit_btn_cancel.setGeometry(QtCore.QRect(10, 300, 141, 21))
        self.dataedit_btn_cancel.setCheckable(False)
        self.dataedit_btn_cancel.setObjectName("dataedit_btn_cancel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Панель администрирования || "))
        self.label1.setText(_translate("MainWindow", "Фамилия:"))
        self.label2.setText(_translate("MainWindow", "Имя:"))
        self.label3.setText(_translate("MainWindow", "Отчество:"))
        self.label4.setText(_translate("MainWindow", "Звание:"))
        self.label9.setText(_translate("MainWindow", "Серия:"))
        self.label10.setText(_translate("MainWindow", "Номер:"))
        self.label11.setText(_translate("MainWindow", "Дата выдачи:"))
        self.label8.setText(_translate("MainWindow", "Информация об удостоверении"))
        self.label5.setText(_translate("MainWindow", "Дата принятия на службу:"))
        self.label6.setText(_translate("MainWindow", "Отдел:"))
        self.label7.setText(_translate("MainWindow", "Должность:"))
        self.label12.setText(_translate("MainWindow", "----------------------------------------------"))
        self.label13.setText(_translate("MainWindow", "Зарплата"))
        self.label14.setText(_translate("MainWindow", "Контрольная сумма:"))
        self.dataedit_btn_confirm.setText(_translate("MainWindow", "Добавить"))
        self.label1_2.setText(_translate("MainWindow", "ID:"))
        self.dataedit_btn_cancel.setText(_translate("MainWindow", "Отмена"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
